#!/bin/zsh

tag="cli-${PHP_VERSION:=74}"

source ~/bin/image-utils.sh

docker run \
    --rm \
    -it \
    --init \
    --user $XIGEN_HOST_USERID:$XIGEN_HOST_GROUPID \
    --volume $XIGEN_MOUNTPOINT:$(pwd) \
    --workdir=$(pwd) \
    xigen/php:$tag php "$@"
